### ISSUE TITLE
Add support for Windows 11 24h2 Actions center

### ISSUE THREAD

**Issue by HelloTech2** [ramensoftware/windows-11-notification-center-styling-guide#10]
As u can see, the actions center from W11 24h2 ``in my case 26100.2`` is not affected by the mod
add a fix for this pls
![image](https://github.com/user-attachments/assets/43a663ee-61d5-471f-a928-41b99e2c8ee6)

**Comment by bbmaster123** [comment]
iirc the action center is supposed to be migrating from uwp to winui3, and its also possible the targets have changed
I don't have 24h2 anymore since I reset my vm, could you do a quick test and check if the following style works?

```
Border
Background=Red
```

and could you also check that it still runs under shellexperiencehost.exe if possible?

thanks :)

**Comment by m417z** [comment]
See the following issue: https://github.com/ramensoftware/windhawk-mods/issues/909.
It looks like adding `ShellHost.exe` to the mod's inclusion list in the advanced options works for now.

**Comment by HelloTech2** [comment]
sorry for being late but I tested this theme and work in the notification center and actions center
![image](https://github.com/user-attachments/assets/5e651ed7-8f07-421e-bbb7-10ba29c5039c)

**Comment by HelloTech2** [comment]
Also works for the tile menus
![image](https://github.com/user-attachments/assets/a543a45d-cd58-4046-a8b5-5fa01d54d2a0)

**Comment by HelloTech2** [comment]
I tested the TranslucentShell theme and now works, I'll see if the effect disappears or not as it happened with the red one.
![image](https://github.com/user-attachments/assets/b9cb20bc-69a2-4863-8c45-8e6bb860d055)

**Comment by bbmaster123** [comment]
sorry I was doing printer stuff...
great! did you need to add shellhost.exe to get it to work?
let me know if you can notice or log what triggers the effect to stop, I would lean towards some sort of energy saver mode for the exe but maybe its just some other bug

**Comment by m417z** [comment]
Support for the action center in Windows 11 version 24H2 was added in version 1.1.3 of the mod.
