### ISSUE TITLE
Windows 11 Notification Center Styler - Move Notifications to Bottom

### ISSUE THREAD

**Issue by JFMugen** [ramensoftware/windows-11-notification-center-styling-guide#17]
Hey there, notifications always appear at the top of the notifications bar, which looks weird and harder to use. 

![SS241110153441](https://github.com/user-attachments/assets/b67c5537-b2c6-47f8-8976-82977421caa5)

Wouldn't it be much better if we move them to the bottom so it would be easier to use? Like this lazy edit

![SS241111155947](https://github.com/user-attachments/assets/824b23d1-6d7a-4d66-9c9f-83722ba5e728)

_*tag the mod's author using their GitHub handle_ -> @m417z

**Comment by m417z** [comment]
Hi, since it's not a mod enhancement suggestion, I moved it to a more appropriate place - notification center styling guide.

Windows 11 Notification Center Styler is designed to allow settings styles for UI elements, not for doing specific things like this one, which perhaps can be achieved via styles. It could be a suggestion for a new mod, though.

**Comment by JFMugen** [comment]
> Hi, since it's not a mod enhancement suggestion, I moved it to a more appropriate place - notification center styling guide.

Fair. I guess instead of a new mod maybe it can be part of this styling guide as well, just to keep things compact. 

Or would you want me to open a new mod suggestion for this?

**Comment by m417z** [comment]
I don't plan on working on it, but you can create a new mod suggestion, sure. Also, if you find a way to do it with styles, a contribution to the styling guide is also welcome.

**Comment by bbmaster123** [comment]
@JFMugen 
try this:
```
Target:
Grid#NotificationCenterGrid
Style:
VerticalAlignment=2
```
![image](https://github.com/user-attachments/assets/db42e186-e5f8-4edb-9f71-e59f3c57744b)

I tested and it does grow/shrink when notifications are received/dismissed

**Comment by JFMugen** [comment]
@bbmaster123 I was just trying to set something myself with UWPSpy tool and failing, thank you very much :) 

Just asking of curiosity, when I change vertical alignment manually with Spy tool, it doesn't work. What might be the problem? 

@m417z you might want to add this to the styling guide maybe?

**Comment by bbmaster123** [comment]
@JFMugen 
I'm not exactly sure without more detail. Did you select the target, change the dropdown (or double click on) to VerticalAlignment? Did you type 2 in the box and click set? Did you disable windhawk first?

Also, if you haven't had a chance yet, please take a look at my uwpspy guide [here](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md)

> you might want to add this to the styling guide maybe?

for sure, I'll take care of it :)

**Comment by JFMugen** [comment]
@bbmaster123 See here, VerticalAlignment is 2 but it's still long. Everything in Windhawk is disabled as well. 

![SS241112194954](https://github.com/user-attachments/assets/2cb1d766-e7dc-46f5-9810-2618a8a2790a)

Anyway I probably won't need it anymore as I am happy with everything right now, thank you again for the help ^^
