### ISSUE TITLE
Remove shadow from Grid

### ISSUE THREAD

**Issue by AsvnDG** [ramensoftware/windows-11-notification-center-styling-guide#4]
Hi,

I want to remove Shadow attribute from Grid (notification, calendar, etc), but don't know what to target/style
If I manually remove Shadow attribute using UWPSpy, the shadow will gone

Here is the before after removing the shadow using UWPSpy for Calendar Grid

Before:
![Before](https://github.com/ramensoftware/windows-11-notification-center-styling-guide/assets/173966283/42e6b386-9dbd-4a2e-94c8-1e32f0f30cfc)

After:
![After](https://github.com/ramensoftware/windows-11-notification-center-styling-guide/assets/173966283/00318b31-936c-46e3-ac4f-8c2d3e5c4269)

**Comment by m417z** [comment]
According to the screenshot, try:
Target: `Grid#CaneldarCenterGrid`
Style: `Shadow:=`

**Comment by AsvnDG** [comment]
And it works.
![Screenshot 2024-07-06 182228](https://github.com/ramensoftware/windows-11-notification-center-styling-guide/assets/173966283/d332f6b2-a4f8-48a4-b4a5-5817e7acbaee)

Thank you!
