### ISSUE TITLE
Edit x position

### ISSUE THREAD

**Issue by sealevelcain** [ramensoftware/windows-11-notification-center-styling-guide#7]
Is it possible to edit the positon of the notification center? I would like it to sit 1200px from the right edge.

I managed to accomplish this with the start menu by targeting `StartDocked.StartSizingFrame` with the style `Canvas.Left=1200`, however I haven't been able to find the right target to use `Canvas.Right` on the notification center. 

I've been able to move various targets using `Margin` styles, but this makes the notification center move outside of the canvas/frame. 

![Screenshot 2024-08-16 095812](https://github.com/user-attachments/assets/66de395b-eec3-41e6-993c-8d86d82daa20)

**Comment by bbmaster123** [comment]
Unfortunately its not possible to move the canvas right now without making a mod to do that.
You'll notice the canvas for the start menu is fullscreen, but notification center is just the bar on the right
Its the same reason the taskbar needed separate mods for height and icon size, and for vertical taskbar

**Comment by sealevelcain** [comment]
> Unfortunately its not possible to move the canvas right now without making a mod to do that.
> 
> You'll notice the canvas for the start menu is fullscreen, but notification center is just the bar on the right
> 
> Its the same reason the taskbar needed separate mods for height and icon size, and for vertical taskbar
> 
> 

That makes sense, thanks for responding.
